import React from 'react';

const Stress = () => {
  return (
    <div className={`lg:mr-[20rem] max-w-7xl mx-auto mt-10`}>
      <h1 className="text-3xl font-bold mb-4 text-black font-semibold font-serif">Stress, anxiété, phobies</h1>
      <p className="mb-4 font-semibold font-serif">
      More than half of medical consultations in Western societies are due to stress, 
      which is the cause of significant consumption of medications, but also of alcohol or psychotropic drugs.
      </p>
      <img
        src="/src/assets/stress.jpg" 
        alt="Stress, anxiété, phobies"
        className="mb-4 w-full h-[460px]"
      />
      <h2 className="text-2xl text-black font-semibold font-serif mb-3">Stress, anxiety, depression and phobias in a nutshell</h2>
      
      
      <p className="mb-4 font-semibold font-serif">
          Stress: More than half of medical consultations in Western societies are due to stress, 
          with a major impact on well-being. Linked to our lifestyles, the pace of work, and isolation, 
          stress is truly the evil of the century.
          <br />Anxiety is a disorder that can be serious. 
          While occasional anxiety is normal, excessive, persistent anxiety seriously affects quality of life. 
          About 15% of the population is subject to disproportionate fears.
      </p>
     

      <p className="mb-4 font-semibold font-serif">
      Phobias are characterized by an irrational fear linked to a situation, an object, an animal. Phobia creates uncontrollable but conscious anxiety about something that is not in itself dangerous.
      <br />Depression is a chronic illness, with a very specific diagnosis. Not to be confused with depression which corresponds more to temporary sadness or melancholy.  
      </p>

      <h1 className="text-2xl text-black font-semibold font-serif mb-3">Recommended practices against stress, anxiety and phobias</h1>
      <p className="mb-4 font-semibold font-serif">
      Phytotherapy: Many medicinal plants such as St. John's wort, omega 3, 5-HTP, SAMe are said to have a relieving action on stress and anxiety. 
      Be careful, some plants interact with medications. Ask a naturopath for advice to find out which products would be best suited to your situation.
    <br />Massage: Positive short-term results have been observed following massage, including improved mood, sleep and immune function, 
        as well as reduced stress and fatigue.
      </p>

      <p className="mb-4 font-semibold font-serif">
      Yoga: Clinical trials have shown that yoga helps alleviate various disorders, from depression to anxiety, 
      and limits disorders linked to post-traumatic stress.
    <br />Meditation: Numerous clinical trials have shown the benefits of practicing meditation on the management of stress and anxiety.
   <br />Hypnosis: The altered state of consciousness obtained under hypnosis and leading to a deep state of relaxation would help manage states of anxiety and soothe phobias.
      </p>
      <p className="mb-4 font-semibold font-serif">
      EMDR: Eye Movement Desensitization and Reprocessing, or desensitization and reprogramming through eye movements, is a complementary practice particularly recommended in cases of trauma.
    <br />Sophrology, Relaxation: Sophrology and relaxation are gentle methods strongly suggested for relieving everyday stress and anxiety and preparing for an important event (sporting event, operation, exam, interview, driving license, etc.)
   <br />Kinesiology: It would identify and reduce tensions generated by stress.
      </p>
      
    </div>
  );
};

export default Stress;
