version: 2.1
executors:
  default:
    machine: true

jobs:
  build:
    executor: default
    steps:
      - run:
          name: Déploiement au serveur de production
          command: |
            ssh debian@ip"cd freesession && git pull origin"
            ssh debian@ip"cd freesession && sudo docker compose start"
